//
//  LocalizationData.swift
//  raku
//
//  Created by Claude on 2025/1/7.
//

import Foundation

// MARK: - 本地化数据
struct LocalizationData {
    
    /// 获取所有本地化字符串数据
    /// - Returns: 按语言分组的本地化字典
    static func getLocalizedStrings() -> [String: [String: String]] {
        return [
            "zh-CN": getChineseSimplifiedStrings(),
            "en-US": getEnglishStrings()
        ]
    }
    
    // MARK: - 简体中文
    private static func getChineseSimplifiedStrings() -> [String: String] {
        return [
            // 通用文案
            "common_cancel": "取消",
            "common_confirm": "确认",
            "common_save": "保存",
            "common_delete": "删除",
            "common_edit": "编辑",
            "common_done": "完成",
            "common_close": "关闭",
            "common_retry": "重试",
            "common_loading": "加载中...",
            "common_error": "错误",
            "common_success": "成功",
            "common_warning": "警告",
            "common_info": "信息",
            "common_yes": "是",
            "common_no": "否",
            "common_ok": "好的",
            "common_back": "返回",
            "common_next": "下一步",
            "common_previous": "上一步",
            "common_add": "添加",
            "common_remove": "移除",
            "common_search": "搜索",
            "common_filter": "筛选",
            "common_share": "分享",
            "common_export": "导出",
            "common_import": "导入",
            "common_download": "下载",
            "common_upload": "上传",
            "common_settings": "设置",
            "common_help": "帮助",
            "common_about": "关于",
            "common_version": "版本",
            "common_update": "更新",
            "common_refresh": "刷新",
            "common_clear": "清除",
            "common_all": "全部",
            "common_none": "无",
            "common_other": "其他",
            "common_unknown": "未知",
            "common_today": "今天",
            "common_yesterday": "昨天",
            "common_tomorrow": "明天",
            "common_now": "现在",
            "common_recently": "最近",
            
            // 录音管理
            "recording_list_title": "录音列表",
            "recording_list_empty": "暂无录音",
            "recording_list_empty_desc": "点击录音按钮开始您的第一个录音",
            "recording_control_start": "开始录音",
            "recording_control_stop": "停止录音",
            "recording_control_pause": "暂停录音",
            "recording_control_resume": "继续录音",
            "recording_control_play": "播放",
            "recording_status_recording": "录音中",
            "recording_status_paused": "已暂停",
            "recording_status_stopped": "已停止",
            "recording_status_playing": "播放中",
            "recording_action_delete": "删除录音",
            "recording_action_share": "分享录音",
            "recording_action_export": "导出录音",
            "recording_action_download": "下载录音",
            "recording_action_rename": "重命名",
            "recording_delete_confirm_title": "删除录音",
            "recording_delete_confirm_message": "确定要删除这个录音吗？此操作无法撤销。",
            "recording_error_save_failed": "保存录音失败",
            "recording_error_load_failed": "加载录音失败",
            "recording_error_delete_failed": "删除录音失败",
            "recording_error_export_failed": "导出录音失败",
            "recording_success_saved": "录音保存成功",
            "recording_success_deleted": "录音删除成功",
            "recording_success_exported": "录音导出成功",
            "recording_duration_format": "%d秒",
            
            // 录音详情
            "detail_nav_title": "录音详情",
            "detail_nav_back": "返回",
            "detail_tag_edit_title": "编辑标签",
            "detail_tag_current": "当前标签",
            "detail_tag_add": "添加标签",
            "detail_tag_suggested": "常用标签",
            "detail_tag_placeholder": "输入标签名称",
            "detail_tag_saving": "保存中...",
            "detail_tag_save_failed": "保存标签失败，请重试",
            "detail_section_edit_title": "编辑段落",
            "detail_section_edit_mode": "编辑",
            "detail_section_preview_mode": "预览",
            "detail_transcript_original": "原文",
            "detail_transcript_polished": "润色版",
            "detail_transcript_full_view": "查看完整转写",
            "detail_markdown_title": "标题",
            "detail_markdown_bold": "粗体",
            "detail_markdown_italic": "斜体",
            "detail_markdown_list": "列表",
            "detail_markdown_todo": "待办",
            "detail_markdown_quote": "引用",
            "detail_markdown_code": "代码",
            "detail_markdown_divider": "分割线",
            
            // 连接管理
            "connection_status_connected": "已连接",
            "connection_status_disconnected": "未连接",
            "connection_status_connecting": "连接中",
            "connection_config_title": "连接配置",
            "connection_config_device": "设备配置",
            "connection_config_network": "网络配置",
            "connection_error_failed": "连接失败",
            "connection_error_network_unavailable": "网络不可用",
            "connection_error_device_not_found": "未找到设备",
            
            // 首页
            "homepage_title": "首页",
            "homepage_filter_tag": "标签",
            "homepage_filter_space": "空间",
            "homepage_search_placeholder": "搜索录音内容...",
            "homepage_search_empty": "未找到相关内容",
            "homepage_search_empty_desc": "尝试使用其他关键词搜索",
            "homepage_search_loading": "搜索中...",
            "homepage_product_name": "Echo o1",
            "homepage_device_connected": "已连接",
            "homepage_device_disconnected": "未连接",
            
            // 搜索
            "search_title": "搜索",
            "search_placeholder": "输入搜索关键词",
            "search_smart_placeholder": "智能搜索内容、语义、标签...",
            "search_result_empty": "未找到匹配结果",
            "search_result_empty_desc": "请尝试其他搜索词",
            "search_result_count": "找到 %d 个结果",
            "search_history_title": "搜索历史",
            "search_history_clear": "清除历史",
            "search_type_all": "全部",
            "search_type_title": "标题",
            "search_type_content": "内容",
            "search_type_tag": "标签",
            
            // 设置
            "settings_title": "设置",
            "settings_appearance_title": "外观设置",
            "settings_dark_mode": "深色模式",
            "settings_language": "语言",
            "settings_theme": "主题",
            "settings_theme_dark": "深色",
            "settings_theme_light": "浅色",
            "settings_account": "账户",
            "settings_notifications": "通知",
            "settings_database_debug": "数据库调试",
            "settings_recording_title": "录音设置",
            "settings_audio_quality": "音频质量",
            "settings_auto_save": "自动保存",
            "settings_storage_location": "存储位置",
            "settings_privacy_title": "隐私设置",
            "settings_data_collection": "数据收集",
            "settings_analytics": "分析统计",
            "settings_about_title": "关于",
            "settings_app_version": "应用版本",
            "settings_build_number": "构建版本",
            "settings_developer": "开发者",
            "settings_contact": "联系方式",
            "settings_feedback": "意见反馈",
            "settings_rate_app": "给应用评分",
            
            // 导出
            "export_title": "导出",
            "export_format_title": "导出格式",
            "export_format_text": "纯文本",
            "export_format_markdown": "Markdown",
            "export_format_pdf": "PDF",
            "export_format_audio": "音频",
            "export_options_title": "导出选项",
            "export_include_transcript": "包含转写内容",
            "export_include_summary": "包含摘要",
            "export_include_timestamp": "包含时间戳",
            "export_destination_title": "导出目标",
            "export_destination_files": "文件",
            "export_destination_share": "分享",
            "export_destination_cloud": "云端",
            "export_progress_title": "导出进度",
            "export_progress_generating": "生成中...",
            "export_progress_uploading": "上传中...",
            "export_success_title": "导出成功",
            "export_success_message": "文件已成功导出",
            "export_error_title": "导出失败",
            "export_error_message": "导出过程中发生错误",
            "export_error_invalid_format": "不支持的文件格式",
            "export_error_file_size": "文件大小超出限制",
            "export_error_permission": "权限不足",
            
            // 时间格式
            "time_format_duration": "%02d:%02d",
            "time_format_time": "HH:mm",
            "time_format_date": "MM月dd日",
            "time_format_datetime": "yyyy年MM月dd日 HH:mm",
            "time_unit_second": "秒",
            "time_unit_second_short": "秒",
            "time_unit_minute": "分钟",
            "time_unit_hour": "小时",
            "time_unit_day": "天",
            "time_unit_week": "周",
            "time_unit_month": "月",
            "time_unit_year": "年",
            "time_relative_just_now": "刚刚",
            "time_relative_minutes_ago": "%d分钟前",
            "time_relative_hours_ago": "%d小时前",
            "time_relative_days_ago": "%d天前",
            
            // 错误提示
            "error_network_title": "网络错误",
            "error_network_message": "请检查网络连接",
            "error_storage_title": "存储错误",
            "error_storage_message": "存储空间不足",
            "error_storage_full": "存储空间已满",
            "error_permission_title": "权限错误",
            "error_permission_microphone": "需要麦克风权限",
            "error_permission_storage": "需要存储权限",
            "error_file_title": "文件错误",
            "error_file_not_found": "文件未找到",
            "error_file_corrupted": "文件已损坏",
            "error_file_format": "不支持的文件格式",
            "error_unknown_title": "未知错误",
            "error_unknown_message": "发生了未知错误，请重试",
        ]
    }
    
    // MARK: - 英文
    private static func getEnglishStrings() -> [String: String] {
        return [
            // Common
            "common_cancel": "Cancel",
            "common_confirm": "Confirm",
            "common_save": "Save",
            "common_delete": "Delete",
            "common_edit": "Edit",
            "common_done": "Done",
            "common_close": "Close",
            "common_retry": "Retry",
            "common_loading": "Loading...",
            "common_error": "Error",
            "common_success": "Success",
            "common_warning": "Warning",
            "common_info": "Info",
            "common_yes": "Yes",
            "common_no": "No",
            "common_ok": "OK",
            "common_back": "Back",
            "common_next": "Next",
            "common_previous": "Previous",
            "common_add": "Add",
            "common_remove": "Remove",
            "common_search": "Search",
            "common_filter": "Filter",
            "common_share": "Share",
            "common_export": "Export",
            "common_import": "Import",
            "common_download": "Download",
            "common_upload": "Upload",
            "common_settings": "Settings",
            "common_help": "Help",
            "common_about": "About",
            "common_version": "Version",
            "common_update": "Update",
            "common_refresh": "Refresh",
            "common_clear": "Clear",
            "common_all": "All",
            "common_none": "None",
            "common_other": "Other",
            "common_unknown": "Unknown",
            "common_today": "Today",
            "common_yesterday": "Yesterday",
            "common_tomorrow": "Tomorrow",
            "common_now": "Now",
            "common_recently": "Recently",
            
            // Recording Management
            "recording_list_title": "Recordings",
            "recording_list_empty": "No recordings",
            "recording_list_empty_desc": "Tap the record button to start your first recording",
            "recording_control_start": "Start Recording",
            "recording_control_stop": "Stop Recording",
            "recording_control_pause": "Pause Recording",
            "recording_control_resume": "Resume Recording",
            "recording_control_play": "Play",
            "recording_status_recording": "Recording",
            "recording_status_paused": "Paused",
            "recording_status_stopped": "Stopped",
            "recording_status_playing": "Playing",
            "recording_action_delete": "Delete Recording",
            "recording_action_share": "Share Recording",
            "recording_action_export": "Export Recording",
            "recording_action_download": "Download Recording",
            "recording_action_rename": "Rename",
            "recording_delete_confirm_title": "Delete Recording",
            "recording_delete_confirm_message": "Are you sure you want to delete this recording? This action cannot be undone.",
            "recording_error_save_failed": "Failed to save recording",
            "recording_error_load_failed": "Failed to load recording",
            "recording_error_delete_failed": "Failed to delete recording",
            "recording_error_export_failed": "Failed to export recording",
            "recording_success_saved": "Recording saved successfully",
            "recording_success_deleted": "Recording deleted successfully",
            "recording_success_exported": "Recording exported successfully",
            "recording_duration_format": "%ds",
            
            // Recording Detail
            "detail_nav_title": "Recording Details",
            "detail_nav_back": "Back",
            "detail_tag_edit_title": "Edit Tags",
            "detail_tag_current": "Current Tags",
            "detail_tag_add": "Add Tag",
            "detail_tag_suggested": "Suggested Tags",
            "detail_tag_placeholder": "Enter tag name",
            "detail_tag_saving": "Saving...",
            "detail_tag_save_failed": "Failed to save tags, please try again",
            "detail_section_edit_title": "Edit Section",
            "detail_section_edit_mode": "Edit",
            "detail_section_preview_mode": "Preview",
            "detail_transcript_original": "Original",
            "detail_transcript_polished": "Polished",
            "detail_transcript_full_view": "View Full Transcript",
            "detail_markdown_title": "Title",
            "detail_markdown_bold": "Bold",
            "detail_markdown_italic": "Italic",
            "detail_markdown_list": "List",
            "detail_markdown_todo": "Todo",
            "detail_markdown_quote": "Quote",
            "detail_markdown_code": "Code",
            "detail_markdown_divider": "Divider",
            
            // Connection Management
            "connection_status_connected": "Connected",
            "connection_status_disconnected": "Disconnected",
            "connection_status_connecting": "Connecting",
            "connection_config_title": "Connection Config",
            "connection_config_device": "Device Config",
            "connection_config_network": "Network Config",
            "connection_error_failed": "Connection failed",
            "connection_error_network_unavailable": "Network unavailable",
            "connection_error_device_not_found": "Device not found",
            
            // Homepage
            "homepage_title": "Home",
            "homepage_filter_tag": "Tags",
            "homepage_filter_space": "Spaces",
            "homepage_search_placeholder": "Search recordings...",
            "homepage_search_empty": "No matching content found",
            "homepage_search_empty_desc": "Try using different keywords",
            "homepage_search_loading": "Searching...",
            "homepage_product_name": "Echo o1",
            "homepage_device_connected": "Connected",
            "homepage_device_disconnected": "Disconnected",
            
            // Settings
            "settings_title": "Settings",
            "settings_appearance_title": "Appearance",
            "settings_dark_mode": "Dark Mode",
            "settings_language": "Language",
            "settings_theme": "Theme",
            "settings_theme_dark": "Dark",
            "settings_theme_light": "Light",
            "settings_account": "Account",
            "settings_notifications": "Notifications",
            "settings_database_debug": "Database Debug",
            "settings_recording_title": "Recording Settings",
            "settings_audio_quality": "Audio Quality",
            "settings_auto_save": "Auto Save",
            "settings_storage_location": "Storage Location",
            "settings_privacy_title": "Privacy Settings",
            "settings_data_collection": "Data Collection",
            "settings_analytics": "Analytics",
            "settings_about_title": "About",
            "settings_app_version": "App Version",
            "settings_build_number": "Build Number",
            "settings_developer": "Developer",
            "settings_contact": "Contact",
            "settings_feedback": "Feedback",
            "settings_rate_app": "Rate App",
            
            // Search
            "search_title": "Search",
            "search_placeholder": "Enter search keywords",
            "search_smart_placeholder": "Search content, tags...",
            "search_result_empty": "No matching results found",
            "search_result_empty_desc": "Try using different keywords",
            "search_result_count": "Found %d results",
            "search_history_title": "Search History",
            "search_history_clear": "Clear History",
            "search_type_all": "All",
            "search_type_title": "Title",
            "search_type_content": "Content",
            "search_type_tag": "Tags",
            
            // Time units
            "time_unit_second": "second",
            "time_unit_second_short": "s",
            "time_unit_minute": "minute",
            "time_unit_hour": "hour",
            "time_unit_day": "day",
            "time_unit_week": "week",
            "time_unit_month": "month",
            "time_unit_year": "year"
        ]
    }
}