//
//  LocalizationData.swift
//  raku
//
//  Created by Claude on 2025/1/7.
//

import Foundation

// MARK: - 语言配置
struct LanguageConfig {
    let code: String
    let name: String
    let nativeName: String
    let flag: String
}

// MARK: - 本地化数据
struct LocalizationData {
    
    // MARK: - 支持的语言
    static let supportedLanguages: [LanguageConfig] = [
        LanguageConfig(code: "zh-CN", name: "Chinese (Simplified)", nativeName: "简体中文", flag: "🇨🇳"),
        LanguageConfig(code: "en-US", name: "English", nativeName: "English", flag: "🇺🇸"),
        LanguageConfig(code: "ja-JP", name: "Japanese", nativeName: "日本語", flag: "🇯🇵"),
        LanguageConfig(code: "de-DE", name: "German", nativeName: "Deutsch", flag: "🇩🇪"),
        LanguageConfig(code: "fr-FR", name: "French", nativeName: "Français", flag: "🇫🇷")
    ]
    
    // MARK: - 默认语言
    static let defaultLanguage = "en-US"
    
    // MARK: - 语言查找方法
    static func getLanguageConfig(for code: String) -> LanguageConfig? {
        return supportedLanguages.first { $0.code == code }
    }
    
    static func getDisplayName(for code: String) -> String {
        return getLanguageConfig(for: code)?.nativeName ?? code
    }
    
    static func getFlag(for code: String) -> String {
        return getLanguageConfig(for: code)?.flag ?? "🌐"
    }
    
    // MARK: - 系统语言检测
    static func getSystemPreferredLanguage() -> String {
        let preferredLanguages = Locale.preferredLanguages
        
        for preferredLang in preferredLanguages {
            // 检查完全匹配
            if supportedLanguages.contains(where: { $0.code == preferredLang }) {
                return preferredLang
            }
            
            // 检查语言代码匹配（忽略地区）
            let languageCode = String(preferredLang.prefix(2))
            switch languageCode {
            case "zh":
                return "zh-CN"
            case "en":
                return "en-US"
            case "ja":
                return "ja-JP"
            case "de":
                return "de-DE"
            case "fr":
                return "fr-FR"
            default:
                continue
            }
        }
        
        return defaultLanguage
    }
    
    /// 获取所有本地化字符串数据
    /// - Returns: 按语言分组的本地化字典
    static func getLocalizedStrings() -> [String: [String: String]] {
        return [
            "zh-CN": getChineseSimplifiedStrings(),
            "en-US": getEnglishStrings(),
            "ja-JP": getJapaneseStrings(),
            "de-DE": getGermanStrings(),
            "fr-FR": getFrenchStrings()
        ]
    }
    
    // MARK: - 简体中文
    private static func getChineseSimplifiedStrings() -> [String: String] {
        return [
            // 通用文案
            "common_cancel": "取消",
            "common_confirm": "确认",
            "common_save": "保存",
            "common_delete": "删除",
            "common_edit": "编辑",
            "common_done": "完成",
            "common_close": "关闭",
            "common_retry": "重试",
            "common_loading": "加载中...",
            "common_error": "错误",
            "common_success": "成功",
            "common_warning": "警告",
            "common_info": "信息",
            "common_yes": "是",
            "common_no": "否",
            "common_ok": "好的",
            "common_back": "返回",
            "common_next": "下一步",
            "common_previous": "上一步",
            "common_add": "添加",
            "common_remove": "移除",
            "common_search": "搜索",
            "common_filter": "筛选",
            "common_share": "分享",
            "common_export": "导出",
            "common_import": "导入",
            "common_download": "下载",
            "common_upload": "上传",
            "common_settings": "设置",
            "common_help": "帮助",
            "common_about": "关于",
            "common_version": "版本",
            "common_update": "更新",
            "common_refresh": "刷新",
            "common_clear": "清除",
            "common_all": "全部",
            "common_none": "无",
            "common_other": "其他",
            "common_unknown": "未知",
            "common_today": "今天",
            "common_yesterday": "昨天",
            "common_tomorrow": "明天",
            "common_now": "现在",
            "common_recently": "最近",
            
            // 录音管理
            "recording_list_title": "录音列表",
            "recording_list_empty": "暂无录音",
            "recording_list_empty_desc": "点击录音按钮开始您的第一个录音",
            "recording_control_start": "开始录音",
            "recording_control_stop": "停止录音",
            "recording_control_pause": "暂停录音",
            "recording_control_resume": "继续录音",
            "recording_control_play": "播放",
            "recording_status_recording": "录音中",
            "recording_status_paused": "已暂停",
            "recording_status_stopped": "已停止",
            "recording_status_playing": "播放中",
            "recording_action_delete": "删除录音",
            "recording_action_share": "分享录音",
            "recording_action_export": "导出录音",
            "recording_action_download": "下载录音",
            "recording_action_rename": "重命名",
            "recording_delete_confirm_title": "删除录音",
            "recording_delete_confirm_message": "确定要删除这个录音吗？此操作无法撤销。",
            "recording_error_save_failed": "保存录音失败",
            "recording_error_load_failed": "加载录音失败",
            "recording_error_delete_failed": "删除录音失败",
            "recording_error_export_failed": "导出录音失败",
            "recording_success_saved": "录音保存成功",
            "recording_success_deleted": "录音删除成功",
            "recording_success_exported": "录音导出成功",
            "recording_duration_format": "%d秒",
            
            // 录音详情
            "detail_nav_title": "录音详情",
            "detail_nav_back": "返回",
            "detail_tag_edit_title": "编辑标签",
            "detail_tag_current": "当前标签",
            "detail_tag_add": "添加标签",
            "detail_tag_suggested": "常用标签",
            "detail_tag_placeholder": "输入标签名称",
            "detail_tag_saving": "保存中...",
            "detail_tag_save_failed": "保存标签失败，请重试",
            "detail_section_edit_title": "编辑段落",
            "detail_section_edit_mode": "编辑",
            "detail_section_preview_mode": "预览",
            "detail_transcript_original": "原文",
            "detail_transcript_polished": "润色版",
            "detail_transcript_full_view": "查看完整转写",
            "detail_markdown_title": "标题",
            "detail_markdown_bold": "粗体",
            "detail_markdown_italic": "斜体",
            "detail_markdown_list": "列表",
            "detail_markdown_todo": "待办",
            "detail_markdown_quote": "引用",
            "detail_markdown_code": "代码",
            "detail_markdown_divider": "分割线",
            
            // 连接管理
            "connection_status_connected": "已连接",
            "connection_status_disconnected": "未连接",
            "connection_status_connecting": "连接中",
            "connection_config_title": "连接配置",
            "connection_config_device": "设备配置",
            "connection_config_network": "网络配置",
            "connection_error_failed": "连接失败",
            "connection_error_network_unavailable": "网络不可用",
            "connection_error_device_not_found": "未找到设备",
            
            // 首页
            "homepage_title": "首页",
            "homepage_filter_tag": "标签",
            "homepage_filter_space": "空间",
            "homepage_search_placeholder": "搜索录音内容...",
            "homepage_search_empty": "未找到相关内容",
            "homepage_search_empty_desc": "尝试使用其他关键词搜索",
            "homepage_search_loading": "搜索中...",
            "homepage_product_name": "Echo o1",
            "homepage_device_connected": "已连接",
            "homepage_device_disconnected": "未连接",
            
            // 搜索
            "search_title": "搜索",
            "search_placeholder": "输入搜索关键词",
            "search_smart_placeholder": "智能搜索内容、语义、标签...",
            "search_result_empty": "未找到匹配结果",
            "search_result_empty_desc": "请尝试其他搜索词",
            "search_result_count": "找到 %d 个结果",
            "search_history_title": "搜索历史",
            "search_history_clear": "清除历史",
            "search_type_all": "全部",
            "search_type_title": "标题",
            "search_type_content": "内容",
            "search_type_tag": "标签",
            
            // 设置
            "settings_title": "设置",
            "settings_appearance_title": "外观设置",
            "settings_dark_mode": "深色模式",
            "settings_language": "语言",
            "settings_theme": "主题",
            "settings_theme_dark": "深色",
            "settings_theme_light": "浅色",
            "settings_account": "账户",
            "settings_notifications": "通知",
            "settings_database_debug": "数据库调试",
            "settings_recording_title": "录音设置",
            "settings_audio_quality": "音频质量",
            "settings_auto_save": "自动保存",
            "settings_storage_location": "存储位置",
            "settings_privacy_title": "隐私设置",
            "settings_data_collection": "数据收集",
            "settings_analytics": "分析统计",
            "settings_about_title": "关于",
            "settings_app_version": "应用版本",
            "settings_build_number": "构建版本",
            "settings_developer": "开发者",
            "settings_contact": "联系方式",
            "settings_rate_app": "给应用评分",
            
            // 导出
            "export_title": "导出",
            "export_format_title": "导出格式",
            "export_format_text": "纯文本",
            "export_format_markdown": "Markdown",
            "export_format_pdf": "PDF",
            "export_format_audio": "音频",
            "export_options_title": "导出选项",
            "export_include_transcript": "包含转写内容",
            "export_include_summary": "包含摘要",
            "export_include_timestamp": "包含时间戳",
            "export_destination_title": "导出目标",
            "export_destination_files": "文件",
            "export_destination_share": "分享",
            "export_destination_cloud": "云端",
            "export_progress_title": "导出进度",
            "export_progress_generating": "生成中...",
            "export_progress_uploading": "上传中...",
            "export_success_title": "导出成功",
            "export_success_message": "文件已成功导出",
            "export_error_title": "导出失败",
            "export_error_message": "导出过程中发生错误",
            "export_error_invalid_format": "不支持的文件格式",
            "export_error_file_size": "文件大小超出限制",
            "export_error_permission": "权限不足",
            
            // 空间管理
            "space_grid_title": "我的空间",
            "space_add_button": "创建空间",
            "space_add_action": "添加空间",
            "space_empty_title": "还没有空间",
            "space_empty_description": "创建您的第一个空间来开始整理想法",
            "space_create_success": "空间创建成功",
            "space_create_failed": "创建空间失败",
            "space_delete_success": "空间删除成功",
            "space_delete_failed": "删除空间失败",
            
            // 标签管理
            "tag_management_title": "标签管理",
            "tag_management_subtitle": "管理您的标签",
            "tag_add_new": "添加新标签",
            "tag_edit_title": "编辑标签",
            "tag_delete_confirm": "确定要删除这个标签吗？",
            "tag_empty_title": "暂无标签",
            "tag_empty_description": "添加标签来更好地组织您的内容",
            "tag_create_success": "标签创建成功",
            "tag_create_failed": "创建标签失败",
            "tag_update_success": "标签更新成功",
            "tag_update_failed": "更新标签失败",
            "tag_delete_success": "标签删除成功",
            "tag_delete_failed": "删除标签失败",
            
            // 设置菜单
            "settings_tag_management": "标签管理",
            "settings_space_management": "空间管理",
            "settings_data_export": "数据导出",
            "settings_backup_restore": "备份与恢复",
            "settings_privacy_security": "隐私与安全",
            "settings_data_import": "数据导入",
            "settings_feedback": "反馈建议",
            
            // 回收站
            "settings_trash_bin": "回收站",
            "trash_empty": "回收站为空",
            "trash_empty_description": "已删除的录音会在7天后自动永久删除",
            "trash_clear_all": "清空回收站",
            "trash_clear_confirm": "确定要永久删除所有项目吗？此操作无法撤销。",
            "trash_restore": "恢复",
            "trash_delete_permanently": "永久删除",
            "trash_days_remaining": "%d天后删除",
            "trash_deleted_at": "删除于",
            "trash_success_restored": "录音已恢复",
            "trash_success_cleared": "回收站已清空",
            "trash_auto_delete_hint": "点击恢复按钮可恢复录音，7天后自动永久删除",
            
            // 数据导入
            "data_import_title": "数据导入",
            "data_import_description": "从其他应用导入数据",
            "data_import_success": "数据导入成功",
            "data_import_failed": "数据导入失败",
            
            // 用户反馈
            "user_feedback_title": "用户反馈",
            "feedback_suggestions": "反馈建议",
            "feedback_submit": "提交反馈",
            "feedback_description": "告诉我们您的想法和建议",
            
            // 空间编辑
            "edit_space_title": "编辑空间",
            "edit_space_save": "保存修改",
            "edit_space_cancel": "取消编辑",
            "basic_information": "基本信息",
            "space_information": "空间信息",
            
            // 空间模板
            "space_template_custom": "自定义",
            "space_template_title": "模板",
            "space_template_feedback_description": "记录产品想法和用户反馈",
            "space_template_notes_description": "记录想法、笔记和灵感",
            "space_template_project_description": "管理项目任务和进度",
            
            // 时间格式
            "time_format_duration": "%02d:%02d",
            "time_format_time": "HH:mm",
            "time_format_date": "MM月dd日",
            "time_format_date_with_year": "yyyy年MM月dd日",
            "time_format_datetime": "yyyy年MM月dd日 HH:mm",
            "time_format_weekday": "EEEE HH:mm",
            "time_format_month_day": "M月d日 HH:mm",
            "time_format_full_date": "yyyy年M月d日 HH:mm",
            "time_format_minimal_date": "MM.dd",
            "time_unit_second": "秒",
            "time_unit_second_short": "秒",
            "time_unit_minute": "分钟",
            "time_unit_hour": "小时",
            "time_unit_day": "天",
            "time_unit_week": "周",
            "time_unit_month": "月",
            "time_unit_year": "年",
            "time_relative_just_now": "刚刚",
            "time_relative_minutes_ago": "%d分钟前",
            "time_relative_hours_ago": "%d小时前",
            "time_relative_days_ago": "%d天前",
            "time_relative_weeks_ago": "%d周前",
            
            // 错误提示
            "error_network_title": "网络错误",
            "error_network_message": "请检查网络连接",
            "error_storage_title": "存储错误",
            "error_storage_message": "存储空间不足",
            "error_storage_full": "存储空间已满",
            "error_permission_title": "权限错误",
            "error_permission_microphone": "需要麦克风权限",
            "error_permission_storage": "需要存储权限",
            "error_file_title": "文件错误",
            "error_file_not_found": "文件未找到",
            "error_file_corrupted": "文件已损坏",
            "error_file_format": "不支持的文件格式",
            "error_unknown_title": "未知错误",
            "error_unknown_message": "发生了未知错误，请重试",
        ]
    }
    
    // MARK: - 英文
    private static func getEnglishStrings() -> [String: String] {
        return [
            // Common
            "common_cancel": "Cancel",
            "common_confirm": "Confirm",
            "common_save": "Save",
            "common_delete": "Delete",
            "common_edit": "Edit",
            "common_done": "Done",
            "common_close": "Close",
            "common_retry": "Retry",
            "common_loading": "Loading...",
            "common_error": "Error",
            "common_success": "Success",
            "common_warning": "Warning",
            "common_info": "Info",
            "common_yes": "Yes",
            "common_no": "No",
            "common_ok": "OK",
            "common_back": "Back",
            "common_next": "Next",
            "common_previous": "Previous",
            "common_add": "Add",
            "common_remove": "Remove",
            "common_search": "Search",
            "common_filter": "Filter",
            "common_share": "Share",
            "common_export": "Export",
            "common_import": "Import",
            "common_download": "Download",
            "common_upload": "Upload",
            "common_settings": "Settings",
            "common_help": "Help",
            "common_about": "About",
            "common_version": "Version",
            "common_update": "Update",
            "common_refresh": "Refresh",
            "common_clear": "Clear",
            "common_all": "All",
            "common_none": "None",
            "common_other": "Other",
            "common_unknown": "Unknown",
            "common_today": "Today",
            "common_yesterday": "Yesterday",
            "common_tomorrow": "Tomorrow",
            "common_now": "Now",
            "common_recently": "Recently",
            
            // Recording Management
            "recording_list_title": "Recordings",
            "recording_list_empty": "No recordings",
            "recording_list_empty_desc": "Tap the record button to start your first recording",
            "recording_control_start": "Start Recording",
            "recording_control_stop": "Stop Recording",
            "recording_control_pause": "Pause Recording",
            "recording_control_resume": "Resume Recording",
            "recording_control_play": "Play",
            "recording_status_recording": "Recording",
            "recording_status_paused": "Paused",
            "recording_status_stopped": "Stopped",
            "recording_status_playing": "Playing",
            "recording_action_delete": "Delete Recording",
            "recording_action_share": "Share Recording",
            "recording_action_export": "Export Recording",
            "recording_action_download": "Download Recording",
            "recording_action_rename": "Rename",
            "recording_delete_confirm_title": "Delete Recording",
            "recording_delete_confirm_message": "Are you sure you want to delete this recording? This action cannot be undone.",
            "recording_error_save_failed": "Failed to save recording",
            "recording_error_load_failed": "Failed to load recording",
            "recording_error_delete_failed": "Failed to delete recording",
            "recording_error_export_failed": "Failed to export recording",
            "recording_success_saved": "Recording saved successfully",
            "recording_success_deleted": "Recording deleted successfully",
            "recording_success_exported": "Recording exported successfully",
            "recording_duration_format": "%ds",
            
            // Recording Detail
            "detail_nav_title": "Recording Details",
            "detail_nav_back": "Back",
            "detail_tag_edit_title": "Edit Tags",
            "detail_tag_current": "Current Tags",
            "detail_tag_add": "Add Tag",
            "detail_tag_suggested": "Suggested Tags",
            "detail_tag_placeholder": "Enter tag name",
            "detail_tag_saving": "Saving...",
            "detail_tag_save_failed": "Failed to save tags, please try again",
            "detail_section_edit_title": "Edit Section",
            "detail_section_edit_mode": "Edit",
            "detail_section_preview_mode": "Preview",
            "detail_transcript_original": "Original",
            "detail_transcript_polished": "Polished",
            "detail_transcript_full_view": "View Full Transcript",
            "detail_markdown_title": "Title",
            "detail_markdown_bold": "Bold",
            "detail_markdown_italic": "Italic",
            "detail_markdown_list": "List",
            "detail_markdown_todo": "Todo",
            "detail_markdown_quote": "Quote",
            "detail_markdown_code": "Code",
            "detail_markdown_divider": "Divider",
            
            // Connection Management
            "connection_status_connected": "Connected",
            "connection_status_disconnected": "Disconnected",
            "connection_status_connecting": "Connecting",
            "connection_config_title": "Connection Config",
            "connection_config_device": "Device Config",
            "connection_config_network": "Network Config",
            "connection_error_failed": "Connection failed",
            "connection_error_network_unavailable": "Network unavailable",
            "connection_error_device_not_found": "Device not found",
            
            // Homepage
            "homepage_title": "Home",
            "homepage_filter_tag": "Tags",
            "homepage_filter_space": "Spaces",
            "homepage_search_placeholder": "Search recordings...",
            "homepage_search_empty": "No matching content found",
            "homepage_search_empty_desc": "Try using different keywords",
            "homepage_search_loading": "Searching...",
            "homepage_product_name": "Echo o1",
            "homepage_device_connected": "Connected",
            "homepage_device_disconnected": "Disconnected",
            
            // Settings
            "settings_title": "Settings",
            "settings_appearance_title": "Appearance",
            "settings_dark_mode": "Dark Mode",
            "settings_language": "Language",
            "settings_theme": "Theme",
            "settings_theme_dark": "Dark",
            "settings_theme_light": "Light",
            "settings_account": "Account",
            "settings_notifications": "Notifications",
            "settings_database_debug": "Database Debug",
            "settings_recording_title": "Recording Settings",
            "settings_audio_quality": "Audio Quality",
            "settings_auto_save": "Auto Save",
            "settings_storage_location": "Storage Location",
            "settings_privacy_title": "Privacy Settings",
            "settings_data_collection": "Data Collection",
            "settings_analytics": "Analytics",
            "settings_about_title": "About",
            "settings_app_version": "App Version",
            "settings_build_number": "Build Number",
            "settings_developer": "Developer",
            "settings_contact": "Contact",
            "settings_rate_app": "Rate App",
            
            // Search
            "search_title": "Search",
            "search_placeholder": "Enter search keywords",
            "search_smart_placeholder": "Search content, tags...",
            "search_result_empty": "No matching results found",
            "search_result_empty_desc": "Try using different keywords",
            "search_result_count": "Found %d results",
            "search_history_title": "Search History",
            "search_history_clear": "Clear History",
            "search_type_all": "All",
            "search_type_title": "Title",
            "search_type_content": "Content",
            "search_type_tag": "Tags",
            
            // Space Management
            "space_grid_title": "My Spaces",
            "space_add_button": "Create Space",
            "space_add_action": "Add Space",
            "space_empty_title": "No spaces yet",
            "space_empty_description": "Create your first space to start organizing ideas",
            "space_create_success": "Space created successfully",
            "space_create_failed": "Failed to create space",
            "space_delete_success": "Space deleted successfully",
            "space_delete_failed": "Failed to delete space",
            
            // Tag Management
            "tag_management_title": "Tag Management",
            "tag_management_subtitle": "Manage Your Tags",
            "tag_add_new": "Add New Tag",
            "tag_edit_title": "Edit Tag",
            "tag_delete_confirm": "Are you sure you want to delete this tag?",
            "tag_empty_title": "No tags",
            "tag_empty_description": "Add tags to better organize your content",
            "tag_create_success": "Tag created successfully",
            "tag_create_failed": "Failed to create tag",
            "tag_update_success": "Tag updated successfully",
            "tag_update_failed": "Failed to update tag",
            "tag_delete_success": "Tag deleted successfully",
            "tag_delete_failed": "Failed to delete tag",
            
            // Settings Menu
            "settings_tag_management": "Tag Management",
            "settings_space_management": "Space Management",
            "settings_data_export": "Data Export",
            "settings_backup_restore": "Backup & Restore",
            "settings_privacy_security": "Privacy & Security",
            "settings_data_import": "Data Import",
            "settings_feedback": "Feedback",
            
            // Trash Bin
            "settings_trash_bin": "Trash",
            "trash_empty": "Trash is empty",
            "trash_empty_description": "Deleted recordings will be permanently removed after 7 days",
            "trash_clear_all": "Empty Trash",
            "trash_clear_confirm": "Are you sure you want to permanently delete all items? This action cannot be undone.",
            "trash_restore": "Restore",
            "trash_delete_permanently": "Delete Permanently",
            "trash_days_remaining": "Deletes in %d days",
            "trash_deleted_at": "Deleted on",
            "trash_success_restored": "Recording restored",
            "trash_success_cleared": "Trash emptied",
            "trash_auto_delete_hint": "Tap restore button to recover. Auto-delete after 7 days.",
            
            // Data Import
            "data_import_title": "Data Import",
            "data_import_description": "Import data from other applications",
            "data_import_success": "Data imported successfully",
            "data_import_failed": "Data import failed",
            
            // User Feedback
            "user_feedback_title": "User Feedback",
            "feedback_suggestions": "Feedback",
            "feedback_submit": "Submit Feedback",
            "feedback_description": "Tell us your thoughts and suggestions",
            
            // Space Editing
            "edit_space_title": "Edit Space",
            "edit_space_save": "Save Changes",
            "edit_space_cancel": "Cancel Edit",
            "basic_information": "Basic Information",
            "space_information": "Space Information",
            
            // Space Templates
            "space_template_custom": "Custom",
            "space_template_title": "Template",
            "space_template_feedback_description": "Record product ideas and user feedback",
            "space_template_notes_description": "Record ideas, notes and inspiration",
            "space_template_project_description": "Manage project tasks and progress",
            
            // Time Formats
            "time_format_duration": "%02d:%02d",
            "time_format_time": "HH:mm",
            "time_format_date": "MMM dd",
            "time_format_date_with_year": "MMM dd, yyyy",
            "time_format_datetime": "MMM dd, yyyy HH:mm",
            "time_format_weekday": "EEEE HH:mm",
            "time_format_month_day": "MMM d, HH:mm",
            "time_format_full_date": "MMM d, yyyy HH:mm",
            "time_format_minimal_date": "MM.dd",
            "time_unit_second": "second",
            "time_unit_second_short": "s",
            "time_unit_minute": "minute",
            "time_unit_hour": "hour",
            "time_unit_day": "day",
            "time_unit_week": "week",
            "time_unit_month": "month",
            "time_unit_year": "year",
            "time_relative_just_now": "Just now",
            "time_relative_minutes_ago": "%d minutes ago",
            "time_relative_hours_ago": "%d hours ago",
            "time_relative_days_ago": "%d days ago",
            "time_relative_weeks_ago": "%d weeks ago"
        ]
    }
    
    // MARK: - 日文
    private static func getJapaneseStrings() -> [String: String] {
        return [
            // 通用
            "common_cancel": "キャンセル",
            "common_confirm": "確認",
            "common_save": "保存",
            "common_delete": "削除",
            "common_edit": "編集",
            "common_done": "完了",
            "common_close": "閉じる",
            "common_retry": "再試行",
            "common_loading": "読み込み中...",
            "common_error": "エラー",
            "common_success": "成功",
            "common_warning": "警告",
            "common_info": "情報",
            "common_yes": "はい",
            "common_no": "いいえ",
            "common_ok": "OK",
            "common_back": "戻る",
            "common_next": "次へ",
            "common_previous": "前へ",
            "common_add": "追加",
            "common_remove": "削除",
            "common_search": "検索",
            "common_filter": "フィルター",
            "common_share": "共有",
            "common_export": "エクスポート",
            "common_import": "インポート",
            "common_download": "ダウンロード",
            "common_upload": "アップロード",
            "common_settings": "設定",
            "common_help": "ヘルプ",
            "common_about": "情報",
            "common_version": "バージョン",
            "common_update": "更新",
            "common_refresh": "更新",
            "common_clear": "クリア",
            "common_all": "すべて",
            "common_none": "なし",
            "common_other": "その他",
            "common_unknown": "不明",
            "common_today": "今日",
            "common_yesterday": "昨日",
            "common_tomorrow": "明日",
            "common_now": "今",
            "common_recently": "最近",
            
            // 録音管理
            "recording_list_title": "録音リスト",
            "recording_list_empty": "録音がありません",
            "recording_list_empty_desc": "録音ボタンをタップして最初の録音を開始してください",
            "recording_control_start": "録音開始",
            "recording_control_stop": "録音停止",
            "recording_control_pause": "録音一時停止",
            "recording_control_resume": "録音再開",
            "recording_control_play": "再生",
            "recording_status_recording": "録音中",
            "recording_status_paused": "一時停止中",
            "recording_status_stopped": "停止",
            "recording_status_playing": "再生中",
            "recording_action_delete": "録音を削除",
            "recording_action_share": "録音を共有",
            "recording_action_export": "録音をエクスポート",
            "recording_action_download": "録音をダウンロード",
            "recording_action_rename": "名前を変更",
            "recording_delete_confirm_title": "録音を削除",
            "recording_delete_confirm_message": "この録音を削除してもよろしいですか？この操作は取り消せません。",
            "recording_error_save_failed": "録音の保存に失敗しました",
            "recording_error_load_failed": "録音の読み込みに失敗しました",
            "recording_error_delete_failed": "録音の削除に失敗しました",
            "recording_error_export_failed": "録音のエクスポートに失敗しました",
            "recording_success_saved": "録音を保存しました",
            "recording_success_deleted": "録音を削除しました",
            "recording_success_exported": "録音をエクスポートしました",
            "recording_duration_format": "%d秒",
            
            // 録音詳細
            "detail_nav_title": "録音詳細",
            "detail_nav_back": "戻る",
            "detail_tag_edit_title": "タグを編集",
            "detail_tag_current": "現在のタグ",
            "detail_tag_add": "タグを追加",
            "detail_tag_suggested": "おすすめのタグ",
            "detail_tag_placeholder": "タグ名を入力",
            "detail_tag_saving": "保存中...",
            "detail_tag_save_failed": "タグの保存に失敗しました。もう一度お試しください",
            "detail_section_edit_title": "セクションを編集",
            "detail_section_edit_mode": "編集",
            "detail_section_preview_mode": "プレビュー",
            "detail_transcript_original": "元のテキスト",
            "detail_transcript_polished": "修正版",
            "detail_transcript_full_view": "完全な転写を表示",
            
            // 接続管理
            "connection_status_connected": "接続済み",
            "connection_status_disconnected": "未接続",
            "connection_status_connecting": "接続中",
            "connection_config_title": "接続設定",
            "connection_config_device": "デバイス設定",
            "connection_config_network": "ネットワーク設定",
            "connection_error_failed": "接続に失敗しました",
            "connection_error_network_unavailable": "ネットワークが利用できません",
            "connection_error_device_not_found": "デバイスが見つかりません",
            
            // ホーム
            "homepage_title": "ホーム",
            "homepage_filter_tag": "タグ",
            "homepage_filter_space": "スペース",
            "homepage_search_placeholder": "録音を検索...",
            "homepage_search_empty": "一致するコンテンツが見つかりません",
            "homepage_search_empty_desc": "別のキーワードで検索してみてください",
            "homepage_search_loading": "検索中...",
            "homepage_product_name": "Echo o1",
            "homepage_device_connected": "接続済み",
            "homepage_device_disconnected": "未接続",
            
            // 検索
            "search_title": "検索",
            "search_placeholder": "検索キーワードを入力",
            "search_smart_placeholder": "コンテンツ、セマンティック、タグを検索...",
            "search_result_empty": "一致する結果が見つかりません",
            "search_result_empty_desc": "別の検索ワードをお試しください",
            "search_result_count": "%d件の結果が見つかりました",
            "search_history_title": "検索履歴",
            "search_history_clear": "履歴をクリア",
            "search_type_all": "すべて",
            "search_type_title": "タイトル",
            "search_type_content": "コンテンツ",
            "search_type_tag": "タグ",
            
            // 設定
            "settings_title": "設定",
            "settings_appearance_title": "外観設定",
            "settings_dark_mode": "ダークモード",
            "settings_language": "言語",
            "settings_theme": "テーマ",
            "settings_theme_dark": "ダーク",
            "settings_theme_light": "ライト",
            "settings_account": "アカウント",
            "settings_notifications": "通知",
            "settings_database_debug": "データベースデバッグ",
            "settings_recording_title": "録音設定",
            "settings_audio_quality": "音質",
            "settings_auto_save": "自動保存",
            "settings_storage_location": "保存場所",
            "settings_privacy_title": "プライバシー設定",
            "settings_data_collection": "データ収集",
            "settings_analytics": "分析統計",
            "settings_about_title": "このアプリについて",
            "settings_app_version": "アプリバージョン",
            "settings_build_number": "ビルドバージョン",
            "settings_developer": "開発者",
            "settings_contact": "お問い合わせ",
            "settings_rate_app": "アプリを評価",
            
            // スペース管理
            "space_grid_title": "マイスペース",
            "space_add_button": "スペース作成",
            "space_add_action": "スペースを追加",
            "space_empty_title": "スペースがありません",
            "space_empty_description": "最初のスペースを作成してアイデアを整理しましょう",
            "space_create_success": "スペースを作成しました",
            "space_create_failed": "スペースの作成に失敗しました",
            "space_delete_success": "スペースを削除しました",
            "space_delete_failed": "スペースの削除に失敗しました",
            
            // タグ管理
            "tag_management_title": "タグ管理",
            "tag_management_subtitle": "タグを管理",
            "tag_add_new": "新しいタグを追加",
            "tag_edit_title": "タグを編集",
            "tag_delete_confirm": "このタグを削除してもよろしいですか？",
            "tag_empty_title": "タグがありません",
            "tag_empty_description": "タグを追加してコンテンツを整理しましょう",
            "tag_create_success": "タグを作成しました",
            "tag_create_failed": "タグの作成に失敗しました",
            "tag_update_success": "タグを更新しました",
            "tag_update_failed": "タグの更新に失敗しました",
            "tag_delete_success": "タグを削除しました",
            "tag_delete_failed": "タグの削除に失敗しました",
            
            // 設定メニュー
            "settings_tag_management": "タグ管理",
            "settings_space_management": "スペース管理",
            "settings_data_export": "データエクスポート",
            "settings_backup_restore": "バックアップと復元",
            "settings_privacy_security": "プライバシーとセキュリティ",
            "settings_data_import": "データインポート",
            "settings_feedback": "フィードバック",
            
            // ゴミ箱
            "settings_trash_bin": "ゴミ箱",
            "trash_empty": "ゴミ箱は空です",
            "trash_empty_description": "削除された録音は7日後に自動的に完全に削除されます",
            "trash_clear_all": "ゴミ箱を空にする",
            "trash_clear_confirm": "すべてのアイテムを完全に削除してもよろしいですか？この操作は取り消せません。",
            "trash_restore": "復元",
            "trash_delete_permanently": "完全に削除",
            "trash_days_remaining": "%d日後に削除",
            "trash_deleted_at": "削除日",
            "trash_success_restored": "録音を復元しました",
            "trash_success_cleared": "ゴミ箱を空にしました",
            "trash_auto_delete_hint": "復元ボタンをタップして復元。7日後に自動削除されます。",
            
            // データインポート
            "data_import_title": "データインポート",
            "data_import_description": "他のアプリからデータをインポート",
            "data_import_success": "データのインポートが完了しました",
            "data_import_failed": "データのインポートに失敗しました",
            
            // ユーザーフィードバック
            "user_feedback_title": "ユーザーフィードバック",
            "feedback_suggestions": "フィードバック",
            "feedback_submit": "フィードバックを送信",
            "feedback_description": "ご意見やご提案をお聞かせください",
            
            // スペース編集
            "edit_space_title": "スペースを編集",
            "edit_space_save": "変更を保存",
            "edit_space_cancel": "編集をキャンセル",
            "basic_information": "基本情報",
            "space_information": "スペース情報",
            
            // スペーステンプレート
            "space_template_custom": "カスタム",
            "space_template_title": "テンプレート",
            "space_template_feedback_description": "製品のアイデアとユーザーフィードバックを記録",
            "space_template_notes_description": "アイデア、ノート、インスピレーションを記録",
            "space_template_project_description": "プロジェクトのタスクと進捗を管理",
            
            // エクスポート
            "export_title": "エクスポート",
            "export_format_title": "エクスポート形式",
            "export_format_text": "プレーンテキスト",
            "export_format_markdown": "Markdown",
            "export_format_pdf": "PDF",
            "export_format_audio": "音声",
            "export_options_title": "エクスポートオプション",
            "export_include_transcript": "転写内容を含める",
            "export_include_summary": "要約を含める",
            "export_include_timestamp": "タイムスタンプを含める",
            "export_destination_title": "エクスポート先",
            "export_destination_files": "ファイル",
            "export_destination_share": "共有",
            "export_destination_cloud": "クラウド",
            "export_progress_title": "エクスポート進行状況",
            "export_progress_generating": "生成中...",
            "export_progress_uploading": "アップロード中...",
            "export_success_title": "エクスポート成功",
            "export_success_message": "ファイルが正常にエクスポートされました",
            "export_error_title": "エクスポート失敗",
            "export_error_message": "エクスポート中にエラーが発生しました",
            
            // 時間フォーマット
            "time_format_duration": "%02d:%02d",
            "time_format_time": "HH:mm",
            "time_format_date": "M月d日",
            "time_format_date_with_year": "yyyy年M月d日",
            "time_format_datetime": "yyyy年M月d日 HH:mm",
            "time_format_weekday": "EEEE HH:mm",
            "time_format_month_day": "M月d日 HH:mm",
            "time_format_full_date": "yyyy年M月d日 HH:mm",
            "time_format_minimal_date": "MM.dd",
            "time_unit_second": "秒",
            "time_unit_minute": "分",
            "time_unit_hour": "時間",
            "time_unit_day": "日",
            "time_unit_week": "週",
            "time_unit_month": "月",
            "time_unit_year": "年",
            "time_relative_just_now": "たった今",
            "time_relative_minutes_ago": "%d分前",
            "time_relative_hours_ago": "%d時間前",
            "time_relative_days_ago": "%d日前",
            "time_relative_weeks_ago": "%d週間前",
            
            // エラーメッセージ
            "error_network_title": "ネットワークエラー",
            "error_network_message": "ネットワーク接続を確認してください",
            "error_storage_title": "ストレージエラー",
            "error_storage_message": "ストレージ容量が不足しています",
            "error_permission_title": "権限エラー",
            "error_permission_microphone": "マイクへのアクセス権限が必要です",
            "error_permission_storage": "ストレージへのアクセス権限が必要です",
            "error_file_title": "ファイルエラー",
            "error_file_not_found": "ファイルが見つかりません",
            "error_file_corrupted": "ファイルが破損しています",
            "error_unknown_title": "不明なエラー",
            "error_unknown_message": "不明なエラーが発生しました。もう一度お試しください"
        ]
    }
    
    // MARK: - 德文
    private static func getGermanStrings() -> [String: String] {
        return [
            // Allgemein
            "common_cancel": "Abbrechen",
            "common_confirm": "Bestätigen",
            "common_save": "Speichern",
            "common_delete": "Löschen",
            "common_edit": "Bearbeiten",
            "common_done": "Fertig",
            "common_close": "Schließen",
            "common_retry": "Wiederholen",
            "common_loading": "Laden...",
            "common_error": "Fehler",
            "common_success": "Erfolg",
            "common_warning": "Warnung",
            "common_info": "Information",
            "common_yes": "Ja",
            "common_no": "Nein",
            "common_ok": "OK",
            "common_back": "Zurück",
            "common_next": "Weiter",
            "common_previous": "Zurück",
            "common_add": "Hinzufügen",
            "common_remove": "Entfernen",
            "common_search": "Suchen",
            "common_filter": "Filter",
            "common_share": "Teilen",
            "common_export": "Exportieren",
            "common_import": "Importieren",
            "common_download": "Herunterladen",
            "common_upload": "Hochladen",
            "common_settings": "Einstellungen",
            "common_help": "Hilfe",
            "common_about": "Über",
            "common_version": "Version",
            "common_update": "Aktualisieren",
            "common_refresh": "Aktualisieren",
            "common_clear": "Löschen",
            "common_all": "Alle",
            "common_none": "Keine",
            "common_other": "Andere",
            "common_unknown": "Unbekannt",
            "common_today": "Heute",
            "common_yesterday": "Gestern",
            "common_tomorrow": "Morgen",
            "common_now": "Jetzt",
            "common_recently": "Kürzlich",
            
            // Aufnahme-Verwaltung
            "recording_list_title": "Aufnahmeliste",
            "recording_list_empty": "Keine Aufnahmen",
            "recording_list_empty_desc": "Tippen Sie auf den Aufnahmeknopf, um Ihre erste Aufnahme zu starten",
            "recording_control_start": "Aufnahme starten",
            "recording_control_stop": "Aufnahme stoppen",
            "recording_control_pause": "Aufnahme pausieren",
            "recording_control_resume": "Aufnahme fortsetzen",
            "recording_control_play": "Abspielen",
            "recording_status_recording": "Aufnahme läuft",
            "recording_status_paused": "Pausiert",
            "recording_status_stopped": "Gestoppt",
            "recording_status_playing": "Wiedergabe",
            "recording_action_delete": "Aufnahme löschen",
            "recording_action_share": "Aufnahme teilen",
            "recording_action_export": "Aufnahme exportieren",
            "recording_action_download": "Aufnahme herunterladen",
            "recording_action_rename": "Umbenennen",
            "recording_delete_confirm_title": "Aufnahme löschen",
            "recording_delete_confirm_message": "Sind Sie sicher, dass Sie diese Aufnahme löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
            "recording_error_save_failed": "Speichern der Aufnahme fehlgeschlagen",
            "recording_error_load_failed": "Laden der Aufnahme fehlgeschlagen",
            "recording_error_delete_failed": "Löschen der Aufnahme fehlgeschlagen",
            "recording_error_export_failed": "Export der Aufnahme fehlgeschlagen",
            "recording_success_saved": "Aufnahme erfolgreich gespeichert",
            "recording_success_deleted": "Aufnahme erfolgreich gelöscht",
            "recording_success_exported": "Aufnahme erfolgreich exportiert",
            "recording_duration_format": "%ds",
            
            // Aufnahme-Details
            "detail_nav_title": "Aufnahme-Details",
            "detail_nav_back": "Zurück",
            "detail_tag_edit_title": "Tags bearbeiten",
            "detail_tag_current": "Aktuelle Tags",
            "detail_tag_add": "Tag hinzufügen",
            "detail_tag_suggested": "Vorgeschlagene Tags",
            "detail_tag_placeholder": "Tag-Name eingeben",
            "detail_tag_saving": "Speichern...",
            "detail_tag_save_failed": "Speichern der Tags fehlgeschlagen, bitte versuchen Sie es erneut",
            "detail_section_edit_title": "Abschnitt bearbeiten",
            "detail_section_edit_mode": "Bearbeiten",
            "detail_section_preview_mode": "Vorschau",
            "detail_transcript_original": "Original",
            "detail_transcript_polished": "Überarbeitet",
            "detail_transcript_full_view": "Vollständige Transkription anzeigen",
            
            // Verbindungsverwaltung
            "connection_status_connected": "Verbunden",
            "connection_status_disconnected": "Getrennt",
            "connection_status_connecting": "Verbindung wird hergestellt",
            "connection_config_title": "Verbindungskonfiguration",
            "connection_config_device": "Gerätekonfiguration",
            "connection_config_network": "Netzwerkkonfiguration",
            "connection_error_failed": "Verbindung fehlgeschlagen",
            "connection_error_network_unavailable": "Netzwerk nicht verfügbar",
            "connection_error_device_not_found": "Gerät nicht gefunden",
            
            // Startseite
            "homepage_title": "Startseite",
            "homepage_filter_tag": "Tags",
            "homepage_filter_space": "Bereiche",
            "homepage_search_placeholder": "Aufnahmen durchsuchen...",
            "homepage_search_empty": "Keine passenden Inhalte gefunden",
            "homepage_search_empty_desc": "Versuchen Sie es mit anderen Suchbegriffen",
            "homepage_search_loading": "Suchen...",
            "homepage_product_name": "Echo o1",
            "homepage_device_connected": "Verbunden",
            "homepage_device_disconnected": "Getrennt",
            
            // Suche
            "search_title": "Suche",
            "search_placeholder": "Suchbegriffe eingeben",
            "search_smart_placeholder": "Inhalt, Semantik, Tags durchsuchen...",
            "search_result_empty": "Keine passenden Ergebnisse gefunden",
            "search_result_empty_desc": "Versuchen Sie es mit anderen Suchbegriffen",
            "search_result_count": "%d Ergebnisse gefunden",
            "search_history_title": "Suchverlauf",
            "search_history_clear": "Verlauf löschen",
            "search_type_all": "Alle",
            "search_type_title": "Titel",
            "search_type_content": "Inhalt",
            "search_type_tag": "Tags",
            
            // Einstellungen
            "settings_title": "Einstellungen",
            "settings_appearance_title": "Erscheinungsbild",
            "settings_dark_mode": "Dunkler Modus",
            "settings_language": "Sprache",
            "settings_theme": "Design",
            "settings_theme_dark": "Dunkel",
            "settings_theme_light": "Hell",
            "settings_account": "Konto",
            "settings_notifications": "Benachrichtigungen",
            "settings_database_debug": "Datenbank-Debug",
            "settings_recording_title": "Aufnahme-Einstellungen",
            "settings_audio_quality": "Audioqualität",
            "settings_auto_save": "Automatisch speichern",
            "settings_storage_location": "Speicherort",
            "settings_privacy_title": "Datenschutz-Einstellungen",
            "settings_data_collection": "Datensammlung",
            "settings_analytics": "Analytik",
            "settings_about_title": "Über die App",
            "settings_app_version": "App-Version",
            "settings_build_number": "Build-Nummer",
            "settings_developer": "Entwickler",
            "settings_contact": "Kontakt",
            "settings_rate_app": "App bewerten",
            
            // Bereich-Verwaltung
            "space_grid_title": "Meine Bereiche",
            "space_add_button": "Bereich erstellen",
            "space_add_action": "Bereich hinzufügen",
            "space_empty_title": "Noch keine Bereiche",
            "space_empty_description": "Erstellen Sie Ihren ersten Bereich, um Ideen zu organisieren",
            "space_create_success": "Bereich erfolgreich erstellt",
            "space_create_failed": "Fehler beim Erstellen des Bereichs",
            "space_delete_success": "Bereich erfolgreich gelöscht",
            "space_delete_failed": "Fehler beim Löschen des Bereichs",
            
            // Tag-Verwaltung
            "tag_management_title": "Tag-Verwaltung",
            "tag_management_subtitle": "Tags verwalten",
            "tag_add_new": "Neuen Tag hinzufügen",
            "tag_edit_title": "Tag bearbeiten",
            "tag_delete_confirm": "Sind Sie sicher, dass Sie diesen Tag löschen möchten?",
            "tag_empty_title": "Keine Tags",
            "tag_empty_description": "Fügen Sie Tags hinzu, um Ihre Inhalte besser zu organisieren",
            "tag_create_success": "Tag erfolgreich erstellt",
            "tag_create_failed": "Fehler beim Erstellen des Tags",
            "tag_update_success": "Tag erfolgreich aktualisiert",
            "tag_update_failed": "Fehler beim Aktualisieren des Tags",
            "tag_delete_success": "Tag erfolgreich gelöscht",
            "tag_delete_failed": "Fehler beim Löschen des Tags",
            
            // Einstellungsmenü
            "settings_tag_management": "Tag-Verwaltung",
            "settings_space_management": "Bereich-Verwaltung",
            "settings_data_export": "Datenexport",
            "settings_backup_restore": "Sicherung & Wiederherstellung",
            "settings_privacy_security": "Datenschutz & Sicherheit",
            "settings_data_import": "Datenimport",
            "settings_feedback": "Feedback",
            
            // Papierkorb
            "settings_trash_bin": "Papierkorb",
            "trash_empty": "Papierkorb ist leer",
            "trash_empty_description": "Gelöschte Aufnahmen werden nach 7 Tagen endgültig gelöscht",
            "trash_clear_all": "Papierkorb leeren",
            "trash_clear_confirm": "Möchten Sie wirklich alle Elemente endgültig löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
            "trash_restore": "Wiederherstellen",
            "trash_delete_permanently": "Endgültig löschen",
            "trash_days_remaining": "Wird in %d Tagen gelöscht",
            "trash_deleted_at": "Gelöscht am",
            "trash_success_restored": "Aufnahme wiederhergestellt",
            "trash_success_cleared": "Papierkorb geleert",
            "trash_auto_delete_hint": "Tippen Sie auf Wiederherstellen. Automatische Löschung nach 7 Tagen.",
            
            // Datenimport
            "data_import_title": "Datenimport",
            "data_import_description": "Daten aus anderen Anwendungen importieren",
            "data_import_success": "Daten erfolgreich importiert",
            "data_import_failed": "Datenimport fehlgeschlagen",
            
            // Benutzerfeedback
            "user_feedback_title": "Benutzerfeedback",
            "feedback_suggestions": "Feedback",
            "feedback_submit": "Feedback senden",
            "feedback_description": "Teilen Sie uns Ihre Gedanken und Vorschläge mit",
            
            // Bereich bearbeiten
            "edit_space_title": "Bereich bearbeiten",
            "edit_space_save": "Änderungen speichern",
            "edit_space_cancel": "Bearbeitung abbrechen",
            "basic_information": "Grundinformationen",
            "space_information": "Bereich-Informationen",
            
            // Bereich-Vorlagen
            "space_template_custom": "Benutzerdefiniert",
            "space_template_feedback_description": "Produktideen und Benutzerfeedback aufzeichnen",
            "space_template_notes_description": "Ideen, Notizen und Inspiration aufzeichnen",
            "space_template_project_description": "Projektaufgaben und Fortschritt verwalten",
            
            // Export
            "export_title": "Export",
            "export_format_title": "Export-Format",
            "export_format_text": "Klartext",
            "export_format_markdown": "Markdown",
            "export_format_pdf": "PDF",
            "export_format_audio": "Audio",
            "export_options_title": "Export-Optionen",
            "export_include_transcript": "Transkription einschließen",
            "export_include_summary": "Zusammenfassung einschließen",
            "export_include_timestamp": "Zeitstempel einschließen",
            "export_destination_title": "Export-Ziel",
            "export_destination_files": "Dateien",
            "export_destination_share": "Teilen",
            "export_destination_cloud": "Cloud",
            "export_progress_title": "Export-Fortschritt",
            "export_progress_generating": "Generieren...",
            "export_progress_uploading": "Hochladen...",
            "export_success_title": "Export erfolgreich",
            "export_success_message": "Datei wurde erfolgreich exportiert",
            "export_error_title": "Export fehlgeschlagen",
            "export_error_message": "Beim Export ist ein Fehler aufgetreten",
            
            // Zeitformate
            "time_format_duration": "%02d:%02d",
            "time_format_time": "HH:mm",
            "time_format_date": "dd.MM",
            "time_format_date_with_year": "dd.MM.yyyy",
            "time_format_datetime": "dd.MM.yyyy HH:mm",
            "time_format_weekday": "EEEE HH:mm",
            "time_format_month_day": "d.M. HH:mm",
            "time_format_full_date": "d.M.yyyy HH:mm",
            "time_format_minimal_date": "MM.dd",
            "time_unit_second": "Sekunde",
            "time_unit_minute": "Minute",
            "time_unit_hour": "Stunde",
            "time_unit_day": "Tag",
            "time_unit_week": "Woche",
            "time_unit_month": "Monat",
            "time_unit_year": "Jahr",
            "time_relative_just_now": "Gerade eben",
            "time_relative_minutes_ago": "vor %d Minuten",
            "time_relative_hours_ago": "vor %d Stunden",
            "time_relative_days_ago": "vor %d Tagen",
            "time_relative_weeks_ago": "vor %d Wochen",
            
            // Fehlermeldungen
            "error_network_title": "Netzwerkfehler",
            "error_network_message": "Bitte überprüfen Sie Ihre Netzwerkverbindung",
            "error_storage_title": "Speicherfehler",
            "error_storage_message": "Nicht genügend Speicherplatz",
            "error_permission_title": "Berechtigungsfehler",
            "error_permission_microphone": "Mikrofon-Berechtigung erforderlich",
            "error_permission_storage": "Speicher-Berechtigung erforderlich",
            "error_file_title": "Dateifehler",
            "error_file_not_found": "Datei nicht gefunden",
            "error_file_corrupted": "Datei ist beschädigt",
            "error_unknown_title": "Unbekannter Fehler",
            "error_unknown_message": "Ein unbekannter Fehler ist aufgetreten, bitte versuchen Sie es erneut"
        ]
    }
    
    // MARK: - 法文
    private static func getFrenchStrings() -> [String: String] {
        return [
            // Commun
            "common_cancel": "Annuler",
            "common_confirm": "Confirmer",
            "common_save": "Enregistrer",
            "common_delete": "Supprimer",
            "common_edit": "Modifier",
            "common_done": "Terminé",
            "common_close": "Fermer",
            "common_retry": "Réessayer",
            "common_loading": "Chargement...",
            "common_error": "Erreur",
            "common_success": "Succès",
            "common_warning": "Avertissement",
            "common_info": "Information",
            "common_yes": "Oui",
            "common_no": "Non",
            "common_ok": "OK",
            "common_back": "Retour",
            "common_next": "Suivant",
            "common_previous": "Précédent",
            "common_add": "Ajouter",
            "common_remove": "Supprimer",
            "common_search": "Rechercher",
            "common_filter": "Filtrer",
            "common_share": "Partager",
            "common_export": "Exporter",
            "common_import": "Importer",
            "common_download": "Télécharger",
            "common_upload": "Téléverser",
            "common_settings": "Paramètres",
            "common_help": "Aide",
            "common_about": "À propos",
            "common_version": "Version",
            "common_update": "Mettre à jour",
            "common_refresh": "Actualiser",
            "common_clear": "Effacer",
            "common_all": "Tous",
            "common_none": "Aucun",
            "common_other": "Autre",
            "common_unknown": "Inconnu",
            "common_today": "Aujourd'hui",
            "common_yesterday": "Hier",
            "common_tomorrow": "Demain",
            "common_now": "Maintenant",
            "common_recently": "Récemment",
            
            // Gestion des enregistrements
            "recording_list_title": "Liste des enregistrements",
            "recording_list_empty": "Aucun enregistrement",
            "recording_list_empty_desc": "Appuyez sur le bouton d'enregistrement pour commencer votre premier enregistrement",
            "recording_control_start": "Démarrer l'enregistrement",
            "recording_control_stop": "Arrêter l'enregistrement",
            "recording_control_pause": "Suspendre l'enregistrement",
            "recording_control_resume": "Reprendre l'enregistrement",
            "recording_control_play": "Lire",
            "recording_status_recording": "Enregistrement en cours",
            "recording_status_paused": "En pause",
            "recording_status_stopped": "Arrêté",
            "recording_status_playing": "Lecture en cours",
            "recording_action_delete": "Supprimer l'enregistrement",
            "recording_action_share": "Partager l'enregistrement",
            "recording_action_export": "Exporter l'enregistrement",
            "recording_action_download": "Télécharger l'enregistrement",
            "recording_action_rename": "Renommer",
            "recording_delete_confirm_title": "Supprimer l'enregistrement",
            "recording_delete_confirm_message": "Êtes-vous sûr de vouloir supprimer cet enregistrement ? Cette action ne peut pas être annulée.",
            "recording_error_save_failed": "Échec de la sauvegarde de l'enregistrement",
            "recording_error_load_failed": "Échec du chargement de l'enregistrement",
            "recording_error_delete_failed": "Échec de la suppression de l'enregistrement",
            "recording_error_export_failed": "Échec de l'exportation de l'enregistrement",
            "recording_success_saved": "Enregistrement sauvegardé avec succès",
            "recording_success_deleted": "Enregistrement supprimé avec succès",
            "recording_success_exported": "Enregistrement exporté avec succès",
            "recording_duration_format": "%ds",
            
            // Détails de l'enregistrement
            "detail_nav_title": "Détails de l'enregistrement",
            "detail_nav_back": "Retour",
            "detail_tag_edit_title": "Modifier les étiquettes",
            "detail_tag_current": "Étiquettes actuelles",
            "detail_tag_add": "Ajouter une étiquette",
            "detail_tag_suggested": "Étiquettes suggérées",
            "detail_tag_placeholder": "Entrer le nom de l'étiquette",
            "detail_tag_saving": "Sauvegarde...",
            "detail_tag_save_failed": "Échec de la sauvegarde des étiquettes, veuillez réessayer",
            "detail_section_edit_title": "Modifier la section",
            "detail_section_edit_mode": "Modifier",
            "detail_section_preview_mode": "Aperçu",
            "detail_transcript_original": "Original",
            "detail_transcript_polished": "Révisé",
            "detail_transcript_full_view": "Voir la transcription complète",
            
            // Gestion des connexions
            "connection_status_connected": "Connecté",
            "connection_status_disconnected": "Déconnecté",
            "connection_status_connecting": "Connexion en cours",
            "connection_config_title": "Configuration de connexion",
            "connection_config_device": "Configuration de l'appareil",
            "connection_config_network": "Configuration réseau",
            "connection_error_failed": "Échec de la connexion",
            "connection_error_network_unavailable": "Réseau indisponible",
            "connection_error_device_not_found": "Appareil non trouvé",
            
            // Accueil
            "homepage_title": "Accueil",
            "homepage_filter_tag": "Étiquettes",
            "homepage_filter_space": "Espaces",
            "homepage_search_placeholder": "Rechercher des enregistrements...",
            "homepage_search_empty": "Aucun contenu correspondant trouvé",
            "homepage_search_empty_desc": "Essayez avec d'autres mots-clés",
            "homepage_search_loading": "Recherche...",
            "homepage_product_name": "Echo o1",
            "homepage_device_connected": "Connecté",
            "homepage_device_disconnected": "Déconnecté",
            
            // Recherche
            "search_title": "Recherche",
            "search_placeholder": "Entrer les mots-clés de recherche",
            "search_smart_placeholder": "Rechercher contenu, sémantique, étiquettes...",
            "search_result_empty": "Aucun résultat correspondant trouvé",
            "search_result_empty_desc": "Essayez avec d'autres termes de recherche",
            "search_result_count": "%d résultats trouvés",
            "search_history_title": "Historique de recherche",
            "search_history_clear": "Effacer l'historique",
            "search_type_all": "Tous",
            "search_type_title": "Titre",
            "search_type_content": "Contenu",
            "search_type_tag": "Étiquettes",
            
            // Paramètres
            "settings_title": "Paramètres",
            "settings_appearance_title": "Apparence",
            "settings_dark_mode": "Mode sombre",
            "settings_language": "Langue",
            "settings_theme": "Thème",
            "settings_theme_dark": "Sombre",
            "settings_theme_light": "Clair",
            "settings_account": "Compte",
            "settings_notifications": "Notifications",
            "settings_database_debug": "Debug de la base de données",
            "settings_recording_title": "Paramètres d'enregistrement",
            "settings_audio_quality": "Qualité audio",
            "settings_auto_save": "Sauvegarde automatique",
            "settings_storage_location": "Emplacement de stockage",
            "settings_privacy_title": "Paramètres de confidentialité",
            "settings_data_collection": "Collecte de données",
            "settings_analytics": "Analyses",
            "settings_about_title": "À propos de l'app",
            "settings_app_version": "Version de l'app",
            "settings_build_number": "Numéro de build",
            "settings_developer": "Développeur",
            "settings_contact": "Contact",
            "settings_rate_app": "Évaluer l'app",
            
            // Gestion des espaces
            "space_grid_title": "Mes Espaces",
            "space_add_button": "Créer un Espace",
            "space_add_action": "Ajouter un Espace",
            "space_empty_title": "Aucun espace encore",
            "space_empty_description": "Créez votre premier espace pour organiser vos idées",
            "space_create_success": "Espace créé avec succès",
            "space_create_failed": "Échec de la création de l'espace",
            "space_delete_success": "Espace supprimé avec succès",
            "space_delete_failed": "Échec de la suppression de l'espace",
            
            // Gestion des étiquettes
            "tag_management_title": "Gestion des Étiquettes",
            "tag_management_subtitle": "Gérer vos Étiquettes",
            "tag_add_new": "Ajouter une Nouvelle Étiquette",
            "tag_edit_title": "Modifier l'Étiquette",
            "tag_delete_confirm": "Êtes-vous sûr de vouloir supprimer cette étiquette ?",
            "tag_empty_title": "Aucune étiquette",
            "tag_empty_description": "Ajoutez des étiquettes pour mieux organiser votre contenu",
            "tag_create_success": "Étiquette créée avec succès",
            "tag_create_failed": "Échec de la création de l'étiquette",
            "tag_update_success": "Étiquette mise à jour avec succès",
            "tag_update_failed": "Échec de la mise à jour de l'étiquette",
            "tag_delete_success": "Étiquette supprimée avec succès",
            "tag_delete_failed": "Échec de la suppression de l'étiquette",
            
            // Menu des paramètres
            "settings_tag_management": "Gestion des Étiquettes",
            "settings_space_management": "Gestion des Espaces",
            "settings_data_export": "Export de Données",
            "settings_backup_restore": "Sauvegarde et Restauration",
            "settings_privacy_security": "Confidentialité et Sécurité",
            "settings_data_import": "Import de Données",
            "settings_feedback": "Commentaires",
            
            // Corbeille
            "settings_trash_bin": "Corbeille",
            "trash_empty": "La corbeille est vide",
            "trash_empty_description": "Les enregistrements supprimés seront définitivement supprimés après 7 jours",
            "trash_clear_all": "Vider la corbeille",
            "trash_clear_confirm": "Voulez-vous vraiment supprimer définitivement tous les éléments ? Cette action est irréversible.",
            "trash_restore": "Restaurer",
            "trash_delete_permanently": "Supprimer définitivement",
            "trash_days_remaining": "Suppression dans %d jours",
            "trash_deleted_at": "Supprimé le",
            "trash_success_restored": "Enregistrement restauré",
            "trash_success_cleared": "Corbeille vidée",
            "trash_auto_delete_hint": "Appuyez sur restaurer pour récupérer. Suppression auto après 7 jours.",
            
            // Import de données
            "data_import_title": "Import de Données",
            "data_import_description": "Importer des données d'autres applications",
            "data_import_success": "Données importées avec succès",
            "data_import_failed": "Échec de l'import des données",
            
            // Commentaires utilisateur
            "user_feedback_title": "Commentaires Utilisateur",
            "feedback_suggestions": "Commentaires",
            "feedback_submit": "Envoyer un Commentaire",
            "feedback_description": "Partagez vos réflexions et suggestions",
            
            // Édition d'espace
            "edit_space_title": "Modifier l'Espace",
            "edit_space_save": "Enregistrer les Modifications",
            "edit_space_cancel": "Annuler la Modification",
            "basic_information": "Informations de Base",
            "space_information": "Informations de l'Espace",
            
            // Modèles d'espace
            "space_template_custom": "Personnalisé",
            "space_template_feedback_description": "Enregistrer les idées de produit et les commentaires utilisateur",
            "space_template_notes_description": "Enregistrer des idées, notes et inspiration",
            "space_template_project_description": "Gérer les tâches et le progrès du projet",
            
            // Export
            "export_title": "Export",
            "export_format_title": "Format d'export",
            "export_format_text": "Texte brut",
            "export_format_markdown": "Markdown",
            "export_format_pdf": "PDF",
            "export_format_audio": "Audio",
            "export_options_title": "Options d'export",
            "export_include_transcript": "Inclure la transcription",
            "export_include_summary": "Inclure le résumé",
            "export_include_timestamp": "Inclure l'horodatage",
            "export_destination_title": "Destination d'export",
            "export_destination_files": "Fichiers",
            "export_destination_share": "Partager",
            "export_destination_cloud": "Cloud",
            "export_progress_title": "Progression de l'export",
            "export_progress_generating": "Génération...",
            "export_progress_uploading": "Téléversement...",
            "export_success_title": "Export réussi",
            "export_success_message": "Le fichier a été exporté avec succès",
            "export_error_title": "Échec de l'export",
            "export_error_message": "Une erreur s'est produite lors de l'export",
            
            // Formats de temps
            "time_format_duration": "%02d:%02d",
            "time_format_time": "HH:mm",
            "time_format_date": "dd MMM",
            "time_format_date_with_year": "dd MMM yyyy",
            "time_format_datetime": "dd MMM yyyy HH:mm",
            "time_format_weekday": "EEEE HH:mm",
            "time_format_month_day": "d MMM, HH:mm",
            "time_format_full_date": "d MMM yyyy HH:mm",
            "time_format_minimal_date": "MM.dd",
            "time_unit_second": "seconde",
            "time_unit_minute": "minute",
            "time_unit_hour": "heure",
            "time_unit_day": "jour",
            "time_unit_week": "semaine",
            "time_unit_month": "mois",
            "time_unit_year": "année",
            "time_relative_just_now": "À l'instant",
            "time_relative_minutes_ago": "il y a %d minutes",
            "time_relative_hours_ago": "il y a %d heures",
            "time_relative_days_ago": "il y a %d jours",
            "time_relative_weeks_ago": "il y a %d semaines",
            
            // Messages d'erreur
            "error_network_title": "Erreur réseau",
            "error_network_message": "Veuillez vérifier votre connexion réseau",
            "error_storage_title": "Erreur de stockage",
            "error_storage_message": "Espace de stockage insuffisant",
            "error_permission_title": "Erreur d'autorisation",
            "error_permission_microphone": "Autorisation du microphone requise",
            "error_permission_storage": "Autorisation de stockage requise",
            "error_file_title": "Erreur de fichier",
            "error_file_not_found": "Fichier non trouvé",
            "error_file_corrupted": "Fichier corrompu",
            "error_unknown_title": "Erreur inconnue",
            "error_unknown_message": "Une erreur inconnue s'est produite, veuillez réessayer"
        ]
    }
}